// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bento: dynamic(() => import("./Bento")),
  blog: dynamic(() => import("./Blog")),
  call_to_action: dynamic(() => import("./CallToAction")),
  hero: dynamic(() => import("./Hero")),
  integrations: dynamic(() => import("./Integrations")),
  line_chart: dynamic(() => import("./LineChart")),
  rich_text: dynamic(() => import("./RichText")),
  showcase: dynamic(() => import("./Showcase")),
};
